#!/usr/bin/bash

socat -U - UNIX-CONNECT:/tmp/hypr/$HYPRLAND_INSTANCE_SIGNATURE/.socket2.sock | \
while read -r line; do 
	if [[ $line =~ "activewindow>>"* ]]; then
		[[ $line == "activewindow>>," ]] && echo "" || echo "";
	fi;
	[[ $line =~ "closewindow>>"* ]] && echo ""	
done;



