#!/usr/bin/bash
socat -U - UNIX-CONNECT:$XDG_RUNTIME_DIR/hypr/$HYPRLAND_INSTANCE_SIGNATURE/.socket2.sock | 
	while read -r line; do 
		if [[ "$line" == "submap"*  ]]; then
			if [[ "$line" == *"dummy" ]]; then
				echo ""
			else
				echo ""
			fi
		fi
	done
