#!/bin/bash
STYLE_PATH="/etc/xdg/waybar/styles/${WAYBAR_STYLE}.css"
STYLE_USER_PATH="$HOME/.config/waybar/styles/${WAYBAR_STYLE}.css"
killall waybar;
if [[ -f "${STYLE_USER_PATH}" ]]; then
	waybar --config /etc/xdg/waybar/hyprland --style "${STYLE_USER_PATH}" $@;
else
	if [[ -f "${STYLE_PATH}" ]]; then
		waybar --config /etc/xdg/waybar/hyprland --style "${STYLE_PATH}" $@;
	else
		waybar --config /etc/xdg/waybar/hyprland $@;
	fi
fi
